/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaChildrenLists {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaChildrenLists(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaChildrenLists obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaChildrenLists(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaChildrenLists copy() {
    long cPtr = megaJNI.MegaChildrenLists_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaChildrenLists(cPtr, false);
  }

  public MegaNodeList getFolderList() {
    long cPtr = megaJNI.MegaChildrenLists_getFolderList(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNodeList(cPtr, false);
  }

  public MegaNodeList getFileList() {
    long cPtr = megaJNI.MegaChildrenLists_getFileList(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNodeList(cPtr, false);
  }

  public MegaChildrenLists() {
    this(megaJNI.new_MegaChildrenLists(), true);
  }

}
